//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZwSerialPortAPI.rc
//
#include "../../include/zw_api_res.h"
#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_ZWSERIALPORTAPI_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_ZWSERIALPORTAPI	    107
#define IDI_SMALL				108
#define IDC_ZWSERIALPORTAPI		109
#define IDM_START				200
#define IDM_TEST				201
//#define IDC_MAIN_EDIT	        202
#define IDM_GET_LIB_VER		    203
#define IDM_GET_CAP		        204
#define IDM_ADD_NODE		    205
#define IDM_ADD_NODE_STOP       206
#define IDM_REQ_NODE_INFO       207
#define IDM_SEND_DATA           208
#define IDM_RM_NODE             209
#define IDM_RM_NODE_STOP        210
#define IDM_GET_INFO            211
#define IDM_SET_LEARN_MODE      212
#define IDM_SET_LEARN_MODE_STOP 213
#define IDM_SET_DEFAULT         214
#define IDM_SET_APPL_NODE_INFO  215
#define IDD_COMM_PORT			216
#define IDE_COMM_NUMBER         217
#define IDD_DEST_NODE           218
#define IDC_DEST_NODE           219
#define IDM_SETTING             220
#define IDM_SEND_SEQ_NUM        221
#define IDM_SHOW_TEST_RES       222
#define IDD_STRESS_TEST         223
#define IDC_ST_SW               224
#define IDC_ST_SEQ              225
#define IDC_ST_NU               225
#define IDD_ASSIGN_RR           226
#define IDC_SRC_NODE            227
#define IDC_DST_NODE            228
#define IDM_ASGN_RR             229
#define IDM_RM_RR               230
#define IDD_DEL_RR              231
#define IDC_ROUTING_SLV         232
#define IDM_RESET               233
#define IDM_REP_SEND            234
#define IDM_RM_FAILED_ID        235
#define IDM_RP_FAILED_NODE      236
#define IDM_CHK_FAILED_NODE     237
#define IDD_FAILED_NODE         238
#define IDC_FAILED_ID           239
#define IDM_NEIGHBOR_UPDT       240
#define IDD_MULTI_SND           241
#define IDC_NODE1               242
#define IDC_NODE2               243
#define IDC_NODE3               244
#define IDC_SW_ON               245
#define IDC_SW_OFF              246
#define IDM_MULTI_SND           247
#define IDM_ASGN_SUC_RR         248
#define IDM_RM_SUC_RR           249
#define IDM_NW_UPDT             250
#define IDM_ENABLE_SUC_ID       251
#define IDM_SET_SUC_NODE        252
#define IDM_SEND_SUC_NODE       253
#define IDD_ENABLE_SUC          254
#define IDC_ENA_SUC             255
#define IDC_ENA_SIS             256
#define IDC_DIS_SUC             257
#define IDD_SET_SUC             258
#define IDM_GET_SUC_NODE        259
#define IDM_RP_FAILED_PRI_CTLR  260
#define IDM_RP_FAILED_PRI_CTLR_STOP 261
#define IDM_CTLR_CHG            262
#define IDM_CTLR_CHG_STOP       263
#define IDM_GET_NODES_INFO      264
#define IDD_REPORT              265
#define IDC_REPORT_NODE_ID      266
#define IDM_MULTI_LVL_REP_GET   267
#define IDM_MULTI_LVL_REPORT    268
#define IDM_NAMELOC_REPORT      269
#define IDM_NAMELOC_REP_GET     270
#define IDM_NAMELOC_REP_SET     271
#define IDD_SET_NAMELOC         272
#define IDC_NAME                273
#define IDC_LOCATION            274
#define IDC_LOC_NODE            275
#define IDM_DISP_NODE_DESC      276
#define IDM_CANCEL_OP           277
#define IDD_ML_START_CHANGE     278
#define IDC_ML_DESC             279
#define IDC_ML_UP               280
#define IDC_ML_DOWN             281
#define IDC_ML_NO_CHG           282
#define IDM_BIN_REPORT          283
#define IDM_BIN_REP_GET         284
#define IDM_BIN_SET             285
#define IDD_BIN_SET             286
#define IDC_BIN_DESC            287
#define IDC_BIN_ON              288
#define IDC_BIN_OFF             289
#define IDM_BIN_SNSR_REP        290
#define IDM_BIN_SNSR_GET        291
#define IDD_GROUP_GET           292
#define IDC_GROUP_ID            293
#define IDC_GROUP_DESC          294
#define IDM_GRP_GET             295
#define IDM_GRP_ADD             296
#define IDM_GRP_DEL             297
#define IDD_GROUP_ADD           298
#define IDC_GRP_EP1             299
#define IDC_GRP_EP2             300
#define IDC_GRP_EP3             301
#define IDC_GRP_EP4             302
#define IDC_GRP_EP5             303
#define IDD_GROUP_DEL           304
#define IDM_ML_SNSR_REP         305
#define IDM_ML_SNSR_GET         306
#define IDM_WKUP_SET            307
#define IDM_WKUP_GET            308
#define IDM_WKUP_ALERT          309
#define IDD_WKUP_SET            310
#define IDC_WKUP_DESC           311
#define IDC_WKUP_NODE           312
#define IDC_WKUP_INTERVAL       313
#define IDD_ML_SET              314
#define IDC_ML_LVL              315
#define IDM_MULTI_LVL_SET       316
#define IDC_ML_DUR              317
#define IDM_MULTI_LVL_CHANGE    318
#define IDC_SEC_UP              319
#define IDC_SEC_DOWN            320
#define IDC_SEC_NO_CHG          321
#define IDC_SEC_LVL             322
#define IDM_MULTI_LVL_SUP       323
#define IDM_GRP_SUP             324
#define IDM_GRP_ATV             325
#define IDC_CMD1                326
#define IDC_CMD2                327
#define IDC_CMD3                328
#define IDC_CMD4                329
#define IDC_CMD5                330
#define IDM_GRP_CMD_SUP         331
#define IDM_GRP_CMD_SET         332
#define IDM_GRP_CMD_GET         333
#define IDD_GROUP_CMD_SET       334
#define IDD_GROUP_CMD_GET       335
#define IDD_CFG_SET             336
#define IDC_PARAM_NUM           337
#define IDC_PARAM_SIZE          338
#define IDC_PARAM_VALUE         339
#define IDM_CFG_SET             340
#define IDM_CFG_REP_SETUP       342
#define IDM_CFG_GET             343
#define IDD_CFG_GET             344
#define IDC_PARAM_SINGLE        345
#define IDC_PARAM_RANGE         346
#define IDC_PARAM_NUM_START     347
#define IDC_PARAM_NUM_END       348
#define IDD_QUEUE_CTL           349
#define IDC_Q_ON                350
#define IDC_Q_OFF               351
#define IDM_CMD_Q_CTL_GET       352
#define IDM_CMD_Q_CTL_SET       353
#define IDM_CMD_Q_VIEW          354
#define IDM_CMD_Q_RM            355
#define IDM_PULSE_REPORT        356
#define IDM_PULSE_REP_GET       357
#define IDM_METER_REPORT        358
#define IDM_METER_REP_GET       359
#define IDM_METER_RESET         360
#define IDM_METER_CAP_GET       361
#define IDM_METER_ADMIN_SET     362
#define IDD_SET_ADMIN           363
#define IDC_DESC                364
#define IDM_AV_SET              365
#define IDD_SET_AV              366
#define IDC_PLAY                0x0013
#define IDC_STOP                0x0014
#define IDC_PAUSE               0x0015
#define IDM_AV_GET              367
#define IDM_METER_SUP_GET       368
#define IDD_METER_GET           369
#define IDC_UNIT                370
#define IDD_INIT                371
#define IDC_SAVE_EXIT           372
#define IDC_FROM_FILE           373
#define IDC_FROM_NW             374
#define IDC_OPEN_FILE           375
#define IDE_FILE_NAME           376
#define IDM_SAVE                377
#define IDD_SAVE                378
#define IDM_REC_CMD_SET         379
#define IDM_BASIC_SET           380
#define IDM_BASIC_REP_GET       381
#define IDM_BASIC_REPORT        382
#define IDD_BASIC_SET           383
#define IDC_BASIC_VAL           384
#define IDM_DLCK_OP_REPORT      385
#define IDM_DLCK_OP_REP_GET     386
#define IDM_DLCK_OP_SET         387
#define IDM_DLCK_CFG_GET        388
#define IDM_DLCK_CFG_SET        389
#define IDD_SET_DLCK_OP         390
#define IDC_DLCK_MODE1          391
#define IDC_DLCK_MODE2          392
#define IDC_DLCK_MODE3          393
#define IDC_DLCK_MODE4          394
#define IDC_DLCK_MODE5          395
#define IDC_DLCK_MODE6          396
#define IDC_DLCK_MODE7          397
#define IDD_DLCK_CFG            398
#define IDC_CONST               399
#define IDC_TIMED               400
#define IDC_OUT_HANDLE1         401
#define IDC_OUT_HANDLE2         402
#define IDC_OUT_HANDLE3         403
#define IDC_OUT_HANDLE4         404
#define IDC_IN_HANDLE1          405
#define IDC_IN_HANDLE2          406
#define IDC_IN_HANDLE3          407
#define IDC_IN_HANDLE4          408
#define IDC_SECOND              409
#define IDC_MINUTE              410
#define IDM_USRCOD_GET          411
#define IDM_USRCOD_SET          412
#define IDM_USRCOD_SUP_GET      413
#define IDD_USRCOD_SET          414
#define IDC_USRID               415
#define IDC_USRCOD              416
#define IDC_USRID_STA1          100
#define IDC_USRID_STA2          101
#define IDC_USRID_STA3          102
#define IDC_USRID_STA4          103
#define IDD_USRCOD_GET          421
#define IDM_ALRM_REPORT         422
#define IDM_ALRM_REP_GET        423
#define IDM_ALRM_SET            424
#define IDM_ALRM_SUP_GET        425
#define IDD_ALRM_GET            426
#define IDC_ALRM_TYPE           427
#define IDC_ALRM_LIST           428
#define IDD_ALRM_SET            429
#define IDC_ALRM_ON             430
#define IDC_ALRM_OFF            431
#define IDM_NI_TEST             432
#define IDM_BATTERY_REP_GET     433
#define IDM_BATTERY_REPORT      434
#define IDM_THR_FAN_MD_REPORT   435
#define IDM_THR_FAN_MD_REP_GET  436
#define IDM_THR_FAN_MD_SUP_GET  437
#define IDM_THR_FAN_MD_SET      438
#define IDM_THR_FAN_STA_REPORT  439
#define IDM_THR_FAN_STA_REP_GET 440
#define IDD_THER_FAN_MOD_SET    441
#define IDM_THR_MD_REPORT       442
#define IDM_THR_MD_REP_GET      443
#define IDM_THR_MD_SUP_GET      444
#define IDM_THR_MD_SET          445
#define IDD_THER_MOD_SET        446
#define IDM_THR_OP_STA_REPORT   447
#define IDM_THR_OP_STA_REP_GET  448
#define IDD_THER_SETB_SET       449
#define IDC_SETB_DEG            450
#define IDM_THR_SETB_REP_GET    451
#define IDM_THR_SETB_SET        452
#define IDM_THR_SETB_REPORT     453
#define IDM_THR_SETP_REPORT     454
#define IDM_THR_SETP_REP_GET    455
#define IDM_THR_SETP_SUP_GET    456
#define IDM_THR_SETP_SET        457
#define IDD_THER_SETP_GET       458
#define IDD_THER_SETP_SET       459
#define IDC_SETP_VAL            460
#define IDC_COMBO_UNIT          461
#define IDM_CLOCK_REPORT        462
#define IDM_CLOCK_REP_GET       463
#define IDM_CLOCK_SET           464
#define IDD_CLOCK_SET           465
#define IDC_COMBO_DAY           466
#define IDC_HOUR                467
#define IDD_CLMT_CTL_SCHED_SET  468
#define IDC_HOUR0               469
#define IDC_HOUR1               470
#define IDC_HOUR2               471
#define IDC_HOUR3               472
#define IDC_HOUR4               473
#define IDC_HOUR5               474
#define IDC_HOUR6               475
#define IDC_HOUR7               476
#define IDC_HOUR8               477
#define IDC_MIN0                478
#define IDC_MIN1                479
#define IDC_MIN2                480
#define IDC_MIN3                481
#define IDC_MIN4                482
#define IDC_MIN5                483
#define IDC_MIN6                484
#define IDC_MIN7                485
#define IDC_MIN8                486
#define IDC_DEG0                487
#define IDC_DEG1                488
#define IDC_DEG2                489
#define IDC_DEG3                490
#define IDC_DEG4                491
#define IDC_DEG5                492
#define IDC_DEG6                493
#define IDC_DEG7                494
#define IDC_DEG8                495
#define IDC_COMBO_STA0          496
#define IDC_COMBO_STA1          497
#define IDC_COMBO_STA2          498
#define IDC_COMBO_STA3          499
#define IDC_COMBO_STA4          500
#define IDC_COMBO_STA5          501
#define IDC_COMBO_STA6          502
#define IDC_COMBO_STA7          503
#define IDC_COMBO_STA8          504
#define IDD_CLMT_CTL_SCHED_GET  505
#define IDM_CC_SCHED_REPORT     506
#define IDM_CC_SCHED_REP_GET    507
#define IDM_CC_SCHED_SET        508
#define IDM_CC_SCHED_CHG_REP_GET   509
#define IDM_CC_SCHED_OVR_REP_GET   560
#define IDM_CC_SCHED_OVR_SET       561
#define IDD_CC_SCHED_OVR_SET    562
#define IDD_MUL_CMD_CTL         563
#define IDM_MUL_CMD_ENC_CTL_SET 564
#define IDM_PROT_REPORT         565
#define IDM_PROT_REP_GET        566
#define IDM_PROT_SET            567
#define IDM_PROT_SUP_GET        568
#define IDM_PROT_EC_REP_GET     569
#define IDM_PROT_EC_SET         570
#define IDM_PROT_TMOUT_REP_GET  571
#define IDM_PROT_TMOUT_SET      572
#define IDD_PROT_SET            573
#define IDD_PROT_EC_SET         574
#define IDD_PROT_TMOUT_SET      575
#define IDM_APPL_REPORT         576
#define IDD_IND_SET             577
#define IDC_IND_VAL             578
#define IDM_IND_REPORT          579
#define IDM_IND_REP_GET         580
#define IDM_IND_SET             581
#define IDD_NIF_SEND            582
#define IDM_NIF_SEND            583
#define IDM_MUL_CMD_ENC_CTL_GET 584
#define IDD_MLSNSR_GET          585
#define IDC_COMBO_TYPE          586
#define IDM_ML_SNSR_SUP_GET     587
#define IDD_MLSNSR_UNIT_GET     588
#define IDM_ML_SNSR_UNIT_GET    589
#define IDM_FW_INFO_GET         590
#define IDM_FW_UPDT_REQ         591
#define IDD_FW_UPDT_REQ         592
#define IDC_FW_FILE             593
#define IDC_FW_VID              594
#define IDC_FW_ID               595
#define IDC_FW_TGT              596
#define IDC_FW_FRAG_SZ          597
#define IDD_POLL_CTL            598
#define IDC_USR_TOKEN           599
#define IDC_ITV                 600
#define IDC_POLL_CNT            601
#define IDM_POLL_CTL            602
#define IDM_RM_POLL             603
#define IDD_POLL_RM             604
#define IDC_ID                  605
#define IDM_POWERLVL_REPORT             606
#define IDM_POWERLVL_REP_GET            607
#define IDM_POWERLVL_SET                608
#define IDM_POWERLVL_TESTNODE_SET		609
#define IDM_POWERLVL_TESTNODE_REP_GET   610
#define IDD_POWER_LEVEL_SET       		611
#define IDC_TIMEOUT       				612
#define IDD_POWER_LEVEL_TESTNODE_SET    613
#define IDC_FRAMECOUNT       			614
#define IDC_TESTNODEID       			615
#define IDD_ALRM_EVT_GET                616
#define IDM_ALRM_SUP_EVT_GET            617
#define IDC_EVENT                       618
#define IDM_AUTO_PROG           619
#define IDD_FLASH_PROG_PORT     620
#define IDC_FLASH_PORT          621
#define IDM_PROG_FLASH          622
#define IDD_FW_FILE             623
#define IDM_QUICK_RESET         624
#define IDD_RESET               625

//Radio button
#define IDC_RADIO0              100
#define IDC_RADIO1              101
#define IDC_RADIO2              102
#define IDC_RADIO3              103
#define IDC_RADIO4              104
#define IDC_RADIO5              105
#define IDC_RADIO6              106
#define IDC_RADIO7              107
#define IDC_RADIO8              108
#define IDC_RADIO9              109
#define IDC_RADIO10             110
#define IDC_RADIO11             111
#define IDC_RADIO12             112
#define IDC_RADIO13             113

// Bitmap
#define OPEN_FILE_BITMAP        1


#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
